export enum TauriEvents {
  ADD_SCHEMA_TO_APPLICATION = "add_schema_to_application",
  ADD_USER_TO_TEAM = "add_user_to_team",
  CREATE_NEW_APPLICATION = "create_new_application",
  CREATE_NEW_TEAM = "create_new_team",
  DELETE_APPLICATION = "delete_application",
  DELETE_TEAM = "delete_team",
  FETCH_ACTIVE_USER = "fetch_active_user",
  FETCH_ALL_USERS = "fetch_all_users",
  FETCH_APPLICATION_BY_ID = "fetch_application_by_id",
  FETCH_AUTH_TOKEN = "fetch_auth_token",
  FETCH_ALL_CACHED_ALERTS = "fetch_all_cached_alerts",
  FETCH_CACHED_ALERTS_BY_APPLICATION = "fetch_cached_alerts_by_application",
  FETCH_TEAM_BY_ID = "fetch_team_by_id",
  LOGIN = "login",
  LOGOUT_USER = "logout_user",
  REGISTER_USER = "register_user",
  REMOVE_USER_FROM_TEAM = "remove_user_from_team",
}
